/* 🤖 this file was generated by svg-to-ts*/

export type MultiColorIcon =
  | 'background-1'
  | 'background-login'
  | 'background'
  | 'bg-rad'
  | 'connor-logo';
export interface IMultiColorIcon {
  name: MultiColorIcon;
  data: string;
}
