/* 🤖 this file was generated by svg-to-ts*/

import { IMultiColorIcon } from './svg-multi-color/my-icons.model';

export type IconNameSubset<
  T extends Readonly<IMultiColorIcon[]>
> = T[number]['name'];

export * from './svg-multi-color/cpm-background-1.icon';
export * from './svg-multi-color/cpm-background-login.icon';
export * from './svg-multi-color/cpm-background.icon';
export * from './svg-multi-color/my-icons.model';
