/* 🤖 this file was generated by svg-to-ts*/

import { ISingleColorIcon } from './svg-single-color/my-icons.model';

export type IconNameSubset<
  T extends Readonly<ISingleColorIcon[]>
> = T[number]['name'];

export * from './svg-single-color/cpm-add-user.icon';
export * from './svg-single-color/cpm-chat.icon';
export * from './svg-single-color/cpm-close.icon';
export * from './svg-single-color/cpm-d-type-bug.icon';
export * from './svg-single-color/cpm-d-type-default.icon';
export * from './svg-single-color/cpm-d-type-story.icon';
export * from './svg-single-color/cpm-d-type-task.icon';
export * from './svg-single-color/cpm-dashboard.icon';
export * from './svg-single-color/cpm-dialog-sending.icon';
export * from './svg-single-color/cpm-dialog.icon';
export * from './svg-single-color/cpm-edit.icon';
export * from './svg-single-color/cpm-filter.icon';
export * from './svg-single-color/cpm-logout.icon';
export * from './svg-single-color/cpm-more.icon';
export * from './svg-single-color/cpm-search.icon';
export * from './svg-single-color/cpm-setting.icon';
export * from './svg-single-color/cpm-user.icon';
export * from './svg-single-color/my-icons.model';
