/* 🤖 this file was generated by svg-to-ts*/
export const cpmChat: {
  name: 'chat';
  data: string;
} = {
  name: 'chat',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M3 21l5.7-1.9c5.418 2.737 12.316-1.406 12.3-7.6C21 6.836 17.165 3 12.5 3 6.302 2.984 2.161 9.878 4.9 15.3L3 21z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path d="M3 21l5.7-1.9c5.418 2.737 12.316-1.406 12.3-7.6C21 6.836 17.165 3 12.5 3 6.302 2.984 2.161 9.878 4.9 15.3L3 21z" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`
};
