/* 🤖 this file was generated by svg-to-ts*/
export const cpmEstimate: {
  name: 'estimate';
  data: string;
} = {
  name: 'estimate',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M10.95.89a7.667 7.667 0 10-5.737 14.22A7.667 7.667 0 0010.95.89zM8.012 2.334a5.667 5.667 0 11.139 11.333 5.667 5.667 0 01-.139-11.333zM9 4a1 1 0 10-2 0v4a1 1 0 00.553.894l2.667 1.333a1 1 0 00.894-1.788L9 7.382V4z"/></svg>`
};
