/* 🤖 this file was generated by svg-to-ts*/
export const cpmDTypeStory: {
  name: 'd-type-story';
  data: string;
} = {
  name: 'd-type-story',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12"><path fill-rule="evenodd" clip-rule="evenodd" d="M6 1.75a4.25 4.25 0 100 8.5 4.25 4.25 0 000-8.5zM.25 6a5.75 5.75 0 1111.5-.131A5.75 5.75 0 01.25 6zM6 3.25a.75.75 0 01.75.75v2a.75.75 0 01-1.5 0V4A.75.75 0 016 3.25zm0 4a.75.75 0 000 1.5h.005a.75.75 0 000-1.5H6z"/></svg>`
};
