/* 🤖 this file was generated by svg-to-ts*/
export const cpmDTypeDefault: {
  name: 'd-type-default';
  data: string;
} = {
  name: 'd-type-default',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M19.73 6.317a1 1 0 01-.047 1.413l-9.625 9a1 1 0 01-1.366 0l-4.375-4.09a1 1 0 111.366-1.46l3.692 3.451 8.942-8.361a1 1 0 011.413.047z"/></svg>`
};
