/* 🤖 this file was generated by svg-to-ts*/
export const cpmSearch: {
  name: 'search';
  data: string;
} = {
  name: 'search',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M5.197 5.197a7.5 7.5 0 0111.266 9.852l4.244 4.244a1 1 0 01-1.414 1.414l-4.244-4.244A7.5 7.5 0 015.197 5.197zM10.5 5a5.5 5.5 0 100 11 5.5 5.5 0 000-11z"/></svg>`
};
