/* 🤖 this file was generated by svg-to-ts*/
export const cpmDialogSending: {
  name: 'dialog-sending';
  data: string;
} = {
  name: 'dialog-sending',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M7.293 2.626a1 1 0 011.414 0l4.667 4.667a1 1 0 010 1.414l-4.667 4.667a1 1 0 01-1.414-1.414L10.253 9h-6.92a1 1 0 110-2h6.92l-2.96-2.96a1 1 0 010-1.414z"/></svg>`
};
