/* 🤖 this file was generated by svg-to-ts*/
export const cpmEdit: {
  name: 'edit';
  data: string;
} = {
  name: 'edit',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill-rule="evenodd" clip-rule="evenodd" d="M18 3.879c-.297 0-.583.118-.793.328L4.903 16.511l-.529 2.115 2.115-.529L18.793 5.793A1.123 1.123 0 0018 3.879zm-2.207-1.086a3.121 3.121 0 014.414 4.414l-12.5 12.5a1 1 0 01-.464.263l-4 1a1 1 0 01-1.213-1.213l1-4a1 1 0 01.263-.464l12.5-12.5zM11 20a1 1 0 011-1h9a1 1 0 110 2h-9a1 1 0 01-1-1z"/></svg>`
};
