/* 🤖 this file was generated by svg-to-ts*/
export const cpmLogout: {
  name: 'logout';
  data: string;
} = {
  name: 'logout',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path fill-rule="evenodd" clip-rule="evenodd" d="M3.333 2.667a.667.667 0 00-.666.666v9.334a.667.667 0 00.666.666H6a.667.667 0 010 1.334H3.333a2 2 0 01-2-2V3.333a2 2 0 012-2H6a.667.667 0 010 1.334H3.333zm6.862 1.528c.26-.26.683-.26.943 0l3.333 3.334c.26.26.26.682 0 .942l-3.333 3.334a.667.667 0 11-.943-.943l2.195-2.195H6a.667.667 0 010-1.334h6.39l-2.195-2.195a.667.667 0 010-.943z"/></svg>`
};
