/* 🤖 this file was generated by svg-to-ts*/
export const cpmRefresh: {
  name: 'refresh';
  data: string;
} = {
  name: 'refresh',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g clip-path="url(#clip0_28612_385353)"><path fill-rule="evenodd" clip-rule="evenodd" d="M8.131 5.008a8 8 0 019.544 1.36L20.475 9H17a1 1 0 100 2h5.989a1.004 1.004 0 00.74-.315A.996.996 0 0024 9.99V4a1 1 0 10-2 0v3.688l-2.944-2.767a10 10 0 102.377 10.411 1 1 0 00-1.886-.664A8 8 0 118.13 5.008z"/></g><defs><clipPath id="clip0_28612_385353"><path d="M0 0h24v24H0z"/></clipPath></defs></svg>`
};
