/* 🤖 this file was generated by svg-to-ts*/
export const cpmMore: {
  name: 'more';
  data: string;
} = {
  name: 'more',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12"><path fill-rule="evenodd" clip-rule="evenodd" d="M1.793 5.293a1 1 0 111.414 1.414 1 1 0 01-1.414-1.414zm3.5 0a1 1 0 111.414 1.414 1 1 0 01-1.414-1.414zm3.5 0a1 1 0 111.414 1.414 1 1 0 01-1.414-1.414z"/></svg>`
};
