/* 🤖 this file was generated by svg-to-ts*/

export type SingleColorIcon =
  | 'add-user'
  | 'chat'
  | 'close'
  | 'd-type-bug'
  | 'd-type-default'
  | 'd-type-story'
  | 'd-type-task'
  | 'dashboard'
  | 'dialog-sending'
  | 'dialog'
  | 'edit'
  | 'estimate'
  | 'filter'
  | 'logout'
  | 'more'
  | 'refresh'
  | 'search'
  | 'setting'
  | 'user';
export interface ISingleColorIcon {
  name: SingleColorIcon;
  data: string;
}
